
;; test-report-system-extras.scm
;; Compatibility module for deprecated (tests test-report-system-extras).
;; This file is autogenerated, do not modify by hand.

(define-module (tests test-report-system-extras))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(tests test-report-system-extras)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(tests test-report-extras)' instead.")

(use-modules (tests test-report-extras))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(tests test-report-extras))))