
;; account-piecharts.scm
;; Compatibility module for deprecated (gnucash report standard-reports account-piecharts).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report standard-reports account-piecharts))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report standard-reports account-piecharts)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash reports standard account-piecharts)' instead.")

(use-modules (gnucash reports standard account-piecharts))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash reports standard account-piecharts))))