
;; income-statement.scm
;; Compatibility module for deprecated (gnucash report standard-reports income-statement).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report standard-reports income-statement))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report standard-reports income-statement)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash reports standard income-statement)' instead.")

(use-modules (gnucash reports standard income-statement))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash reports standard income-statement))))