
;; net-charts.scm
;; Compatibility module for deprecated (gnucash report standard-reports net-charts).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report standard-reports net-charts))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report standard-reports net-charts)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash reports standard net-charts)' instead.")

(use-modules (gnucash reports standard net-charts))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash reports standard net-charts))))