
;; migrate-prefs-user.scm
;; Compatibility module for deprecated (migrate-prefs-user).
;; This file is autogenerated, do not modify by hand.

(define-module (migrate-prefs-user))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(migrate-prefs-user)' has been deprecated and will be removed in the future.")
