
;; migrate-prefs.scm
;; Compatibility module for deprecated (migrate-prefs).
;; This file is autogenerated, do not modify by hand.

(define-module (migrate-prefs))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(migrate-prefs)' has been deprecated and will be removed in the future.")
