
;; hello-world.scm
;; Compatibility module for deprecated (gnucash report hello-world).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report hello-world))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report hello-world)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash reports example hello-world)' instead.")

(use-modules (gnucash reports example hello-world))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash reports example hello-world))))