
;; report-gnome.scm
;; Compatibility module for deprecated (gnucash report report-gnome).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report report-gnome))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report report-gnome)' has been deprecated and will be removed in the future.")
