
;; report-system.scm
;; Compatibility module for deprecated (gnucash report report-system).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report report-system))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report report-system)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash report)' instead.")

(use-modules (gnucash report))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash report))))