
;; standard-reports.scm
;; Compatibility module for deprecated (gnucash report standard-reports).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report standard-reports))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report standard-reports)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash reports)' instead.")

(use-modules (gnucash reports))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash reports))))