
;; srfi64-extras.scm
;; Compatibility module for deprecated (gnucash engine test srfi64-extras).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash engine test srfi64-extras))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash engine test srfi64-extras)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(tests srfi64-extras)' instead.")

(use-modules (tests srfi64-extras))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(tests srfi64-extras))))