
;; qif-import.scm
;; Compatibility module for deprecated (gnucash import-export qif-import).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash import-export qif-import))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash import-export qif-import)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash qif-import)' instead.")

(use-modules (gnucash qif-import))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash qif-import))))