
;; account-summary.scm
;; Compatibility module for deprecated (gnucash report standard-reports account-summary).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report standard-reports account-summary))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report standard-reports account-summary)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash reports standard account-summary)' instead.")

(use-modules (gnucash reports standard account-summary))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash reports standard account-summary))))