
;; balsheet-pnl.scm
;; Compatibility module for deprecated (gnucash report standard-reports balsheet-pnl).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report standard-reports balsheet-pnl))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report standard-reports balsheet-pnl)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash reports standard balsheet-pnl)' instead.")

(use-modules (gnucash reports standard balsheet-pnl))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash reports standard balsheet-pnl))))