
;; budget-flow.scm
;; Compatibility module for deprecated (gnucash report standard-reports budget-flow).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report standard-reports budget-flow))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report standard-reports budget-flow)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash reports standard budget-flow)' instead.")

(use-modules (gnucash reports standard budget-flow))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash reports standard budget-flow))))