
;; equity-statement.scm
;; Compatibility module for deprecated (gnucash report standard-reports equity-statement).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report standard-reports equity-statement))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report standard-reports equity-statement)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash reports standard equity-statement)' instead.")

(use-modules (gnucash reports standard equity-statement))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash reports standard equity-statement))))