
;; register.scm
;; Compatibility module for deprecated (gnucash report standard-reports register).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report standard-reports register))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report standard-reports register)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash reports standard register)' instead.")

(use-modules (gnucash reports standard register))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash reports standard register))))