
;; de_DE.scm
;; Compatibility module for deprecated (gnucash tax de_DE).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash tax de_DE))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash tax de_DE)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash locale de_DE tax)' instead.")

(use-modules (gnucash locale de_DE tax))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash locale de_DE tax))))