
;; us.scm
;; Compatibility module for deprecated (gnucash report locale-specific us).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report locale-specific us))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report locale-specific us)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash reports locale-specific us taxtxf)' instead.")

(use-modules (gnucash reports locale-specific us taxtxf))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash reports locale-specific us taxtxf))))