
;; eguile-html-utilities.scm
;; Compatibility module for deprecated (gnucash report eguile-html-utilities).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report eguile-html-utilities))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report eguile-html-utilities)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash eguile)' instead.")

(use-modules (gnucash eguile))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash eguile))))