
;; collectors.scm
;; Compatibility module for deprecated (gnucash report report-system collectors).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report report-system collectors))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report report-system collectors)' has been deprecated and will be removed in the future.")
