
;; budget-balance-sheet.scm
;; Compatibility module for deprecated (gnucash report standard-reports budget-balance-sheet).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report standard-reports budget-balance-sheet))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report standard-reports budget-balance-sheet)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash reports standard budget-balance-sheet)' instead.")

(use-modules (gnucash reports standard budget-balance-sheet))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash reports standard budget-balance-sheet))))