
;; portfolio.scm
;; Compatibility module for deprecated (gnucash report standard-reports portfolio).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report standard-reports portfolio))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report standard-reports portfolio)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash reports standard portfolio)' instead.")

(use-modules (gnucash reports standard portfolio))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash reports standard portfolio))))