
;; reconcile-report.scm
;; Compatibility module for deprecated (gnucash report standard-reports reconcile-report).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report standard-reports reconcile-report))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report standard-reports reconcile-report)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash reports standard reconcile-report)' instead.")

(use-modules (gnucash reports standard reconcile-report))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash reports standard reconcile-report))))