
;; string.scm
;; Compatibility module for deprecated (gnucash import-export string).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash import-export string))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash import-export string)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash string)' instead.")

(use-modules (gnucash string))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash string))))