
;; gettext.scm
;; Compatibility module for deprecated (gnucash gettext).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash gettext))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash gettext)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash core-utils)' instead.")

(use-modules (gnucash core-utils))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash core-utils))))