
;; us.scm
;; Compatibility module for deprecated (gnucash tax us).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash tax us))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash tax us)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash locale us tax)' instead.")

(use-modules (gnucash locale us tax))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash locale us tax))))