
;; unittest-support.scm
;; Compatibility module for deprecated (gnucash unittest-support).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash unittest-support))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash unittest-support)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(tests unittest-support)' instead.")

(use-modules (tests unittest-support))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(tests unittest-support))))