
;; business-reports.scm
;; Compatibility module for deprecated (gnucash report business-reports).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report business-reports))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report business-reports)' has been deprecated and will be removed in the future.")
