
;; customer-summary.scm
;; Compatibility module for deprecated (gnucash report customer-summary).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report customer-summary))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report customer-summary)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash reports standard customer-summary)' instead.")

(use-modules (gnucash reports standard customer-summary))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash reports standard customer-summary))))