
;; invoice.scm
;; Compatibility module for deprecated (gnucash report invoice).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report invoice))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report invoice)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash reports standard invoice)' instead.")

(use-modules (gnucash reports standard invoice))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash reports standard invoice))))