
;; receipt.scm
;; Compatibility module for deprecated (gnucash report receipt).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report receipt))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report receipt)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash reports standard receipt)' instead.")

(use-modules (gnucash reports standard receipt))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash reports standard receipt))))