
;; stylesheets.scm
;; Compatibility module for deprecated (gnucash report stylesheets).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report stylesheets))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report stylesheets)' has been deprecated and will be removed in the future.")
