
;; stylesheet-head-or-tail.scm
;; Compatibility module for deprecated (gnucash report stylesheet-head-or-tail).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report stylesheet-head-or-tail))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report stylesheet-head-or-tail)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash report stylesheets head-or-tail)' instead.")

(use-modules (gnucash report stylesheets head-or-tail))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash report stylesheets head-or-tail))))