
;; stylesheet-plain.scm
;; Compatibility module for deprecated (gnucash report stylesheet-plain).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report stylesheet-plain))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report stylesheet-plain)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash report stylesheets plain)' instead.")

(use-modules (gnucash report stylesheets plain))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash report stylesheets plain))))