
;; taxinvoice.scm
;; Compatibility module for deprecated (gnucash report taxinvoice).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report taxinvoice))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report taxinvoice)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash reports standard taxinvoice)' instead.")

(use-modules (gnucash reports standard taxinvoice))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash reports standard taxinvoice))))