
;; utility-reports.scm
;; Compatibility module for deprecated (gnucash report utility-reports).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report utility-reports))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report utility-reports)' has been deprecated and will be removed in the future.")
