
;; view-column.scm
;; Compatibility module for deprecated (gnucash report view-column).
;; This file is autogenerated, do not modify by hand.

(define-module (gnucash report view-column))

(issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Module '(gnucash report view-column)' has been deprecated and will be removed in the future.")
                (issue-deprecation-warning "* WARN <gnc-guile-deprecation> *: Use module '(gnucash reports standard view-column)' instead.")

(use-modules (gnucash reports standard view-column))

(let ((i (module-public-interface (current-module))))
     (module-use! i (resolve-interface '(gnucash reports standard view-column))))